### ISSUE TITLE
Exporting to the PDF

### ISSUE THREAD

**Issue by pervoj** [bertob/guadec2021-slides#1]
@bertob Hello, how was the presentation exported to the PDF from the SVG? Thanks.

Good talk, btw. :)

**Comment by bertob** [comment]
Using the Vector Slicer app: https://flathub.org/apps/details/org.gnome.design.VectorSlicer

I'm not sure if the current release of Vector Slicer works properly though, I'm using master.

**Comment by pervoj** [comment]
Thanks! It is working.
